version: "3.3"
services:
  modmon:
    build: .
    image: "jannetta/modmon:0.0.2"
    container_name: modmon
    networks:
      mvc_network:
        ipv4_address: 172.16.1.2
    ports:
      - "4567:4567"
      - "8889:8888"
    volumes:
      - ~/DOCKERVOLUMES/modmon:/modmon
      - ~/DOCKERVOLUMES/jupyterlab:/root
  postgres:
    image: "postgres"
    container_name: postgresql
    networks:
      mvc_network:
        ipv4_address: 172.16.1.3
    ports:
      - "5432:5432"
    volumes:
      - ~/DOCKERVOLUMES/postgrestore:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

volumes:
  modmon:
  postgrestore:
  jupyterlab:

networks:
  mvc_network:
    external: true
