version: "3.3"
services:
  modmon:
    build: .
    image: "jannetta/modmon:0.0.5"
    container_name: modmon
    networks:
      mvc_network:
        ipv4_address: 172.16.1.2
    ports:
      - "85:4567"
      - "8080:8888"
    volumes:
      - modmon:/modmon
      - jupyter:/root
  
  postgres:
    image: "postgres:12.6"
    container_name: postgresql
    networks:
      mvc_network:
        ipv4_address: 172.16.1.3
    ports:
      - "5432:5432"
    volumes:
      - postgrestore:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

volumes:
  modmon:
  jupyter:
  postgrestore:

networks:
  mvc_network:
    external: true
